#version 460
#extension GL_GOOGLE_include_directive : require
layout(local_size_x=8,local_size_y=8) in;
layout(set=0,binding=3,rgba8) uniform writeonly image2D outputColor;
#include "pt_rr_images.glsl"
layout(push_constant) uniform Constants {
    vec4 originNear,forwardFar,rightProjection,upProjection;
    vec4 sunExposure,parameters,sunRadiance,sampling;
} pc;
void main() {
    ivec2 p=ivec2(gl_GlobalInvocationID.xy);
    if(any(greaterThanEqual(p,imageSize(rrNoisy)))) return;
    vec3 x=max(imageLoad(rrNoisy,p).rgb*pc.sunExposure.w,vec3(0));
    vec3 c=pow(clamp((x*(2.51*x+0.03))/(x*(2.43*x+0.59)+0.14),0,1),vec3(1.0/2.2));
    imageStore(outputColor,p,vec4(c,1));
}
