"""Generate VQ3 Evolution's own toroidal void/cluster rank tile (NumPy).

Print the reproducible native C table to stdout; no external texture/package.
The progressive thresholds are tested spectrally by pt_sampling_quality_check.py.
"""
import numpy as np

SIZE = 64


def generate():
    rng = np.random.default_rng(73127)
    a = np.arange(SIZE)
    d = np.minimum(a, SIZE-a)
    kernel = np.exp(-(d[:, None]**2+d[None, :]**2)/(2*1.5**2))
    occupied = np.zeros((SIZE, SIZE), dtype=bool)
    occupied.flat[rng.choice(SIZE*SIZE, SIZE*SIZE//10, replace=False)] = True
    density = np.fft.ifft2(np.fft.fft2(occupied)*np.fft.fft2(kernel)).real

    def change(index, sign):
        y, x = divmod(int(index), SIZE)
        density[:] += sign*np.roll(kernel, (y, x), (0, 1))
        occupied[y, x] = sign > 0

    for _ in range(SIZE*SIZE):
        cluster = np.argmax(np.where(occupied, density, -np.inf))
        change(cluster, -1)
        void = np.argmin(np.where(occupied, np.inf, density))
        change(void, 1)
        if cluster == void:
            break
    else:
        raise RuntimeError("Void/cluster seed did not converge")
    seed, seed_density = occupied.copy(), density.copy()
    ranks = np.empty((SIZE, SIZE), dtype=np.uint32)
    for rank in range(int(seed.sum())-1, -1, -1):
        index = np.argmax(np.where(occupied, density, -np.inf))
        ranks.flat[index] = rank
        change(index, -1)
    occupied[:], density[:] = seed, seed_density
    for rank in range(int(seed.sum()), SIZE*SIZE):
        index = np.argmin(np.where(occupied, np.inf, density))
        ranks.flat[index] = rank
        change(index, 1)
    return ranks


if __name__ == "__main__":
    ranks = generate().ravel()
    print("/* Generated by tools/generate-pt-blue-noise.py; native rank data. */")
    print("static const uint32_t pt_blue_noise[4096] = {")
    for start in range(0, len(ranks), 16):
        print("    " + ", ".join(map(str, ranks[start:start+16])) + ",")
    print("};")
